import {
  NO_FLAGS,
  emptyFoodGroupServes,
  emptyNutrientVector,
  type FoodInput,
  type ProfileInput,
} from '@diet-tracker/shared'

/**
 * The two personas from docs/PLAN.md, with the profiles that produce the golden targets in
 * nutrition-engine/references/targets.md. Local use only; never run the seed against
 * production.
 */
export const SEED_USERS: { email: string; password: string; profile: ProfileInput }[] = [
  {
    email: 'finn@example.com',
    password: 'finn-password',
    profile: {
      sex: 'male',
      dob: '1998-06-15',
      heightCm: 178,
      weightKg: 75,
      bodyFatPct: null,
      goal: 'gain',
      pace: 'lean',
      goalWeightKg: 80,
      activity: 'high',
      trainingType: 'combat',
      trainingDaysPerWeek: 6,
      dietPattern: 'omnivore',
      allergies: [],
      dislikes: ['liver'],
      timezone: 'Europe/London',
      units: 'metric',
      flags: NO_FLAGS,
    },
  },
  {
    email: 'tess@example.com',
    password: 'tess-password',
    profile: {
      sex: 'female',
      dob: '1996-04-02',
      heightCm: 160,
      weightKg: 50,
      bodyFatPct: null,
      goal: 'lose',
      pace: 'gentle',
      goalWeightKg: 48,
      activity: 'moderate',
      trainingType: 'general',
      trainingDaysPerWeek: 3,
      dietPattern: 'omnivore',
      allergies: ['shellfish'],
      dislikes: ['coriander'],
      timezone: 'Europe/London',
      units: 'metric',
      flags: NO_FLAGS,
    },
  },
]

/**
 * A few library foods per persona so My foods is not empty on first open. Per-100g values
 * are typical label figures; per-serving ones describe one scoop or one piece.
 */
export const SEED_FOODS: Record<string, FoodInput[]> = {
  'finn@example.com': [
    {
      name: 'Whey protein shake',
      brand: null,
      basis: 'per_serving',
      servingGrams: 35,
      servingLabel: '1 scoop',
      nutrients: {
        ...emptyNutrientVector(),
        energy_kcal: 130,
        protein_g: 25,
        carbs_g: 3,
        fat_g: 2,
        sugar_g: 2,
        saturated_fat_g: 1.2,
        sodium_mg: 120,
        calcium_mg: 150,
        potassium_mg: 180,
      },
      foodGroups: { ...emptyFoodGroupServes(), dairy_or_alt: 0.5 },
    },
    {
      name: 'Rolled oats',
      brand: null,
      basis: 'per_100g',
      servingGrams: null,
      servingLabel: null,
      nutrients: {
        ...emptyNutrientVector(),
        energy_kcal: 380,
        protein_g: 13,
        carbs_g: 60,
        fat_g: 7,
        fiber_g: 10,
        sugar_g: 1,
        saturated_fat_g: 1.3,
        sodium_mg: 5,
        potassium_mg: 360,
        magnesium_mg: 130,
        iron_mg: 4,
        zinc_mg: 3.5,
        folate_ug: 30,
      },
      foodGroups: { ...emptyFoodGroupServes(), whole_grains: 3.3 },
    },
    {
      name: 'Greek yoghurt, full fat',
      brand: null,
      basis: 'per_100g',
      servingGrams: null,
      servingLabel: null,
      nutrients: {
        ...emptyNutrientVector(),
        energy_kcal: 97,
        protein_g: 9,
        carbs_g: 4,
        fat_g: 5,
        sugar_g: 4,
        saturated_fat_g: 3.3,
        sodium_mg: 35,
        calcium_mg: 110,
        potassium_mg: 140,
        vitamin_b12_ug: 0.5,
        zinc_mg: 0.5,
      },
      foodGroups: { ...emptyFoodGroupServes(), dairy_or_alt: 0.5 },
    },
  ],
  'tess@example.com': [
    {
      name: 'Rolled oats',
      brand: null,
      basis: 'per_100g',
      servingGrams: null,
      servingLabel: null,
      nutrients: {
        ...emptyNutrientVector(),
        energy_kcal: 380,
        protein_g: 13,
        carbs_g: 60,
        fat_g: 7,
        fiber_g: 10,
        sugar_g: 1,
        saturated_fat_g: 1.3,
        sodium_mg: 5,
        potassium_mg: 360,
        magnesium_mg: 130,
        iron_mg: 4,
        zinc_mg: 3.5,
        folate_ug: 30,
      },
      foodGroups: { ...emptyFoodGroupServes(), whole_grains: 3.3 },
    },
    {
      name: 'Banana',
      brand: null,
      basis: 'per_serving',
      servingGrams: 120,
      servingLabel: '1 medium',
      nutrients: {
        ...emptyNutrientVector(),
        energy_kcal: 105,
        protein_g: 1.3,
        carbs_g: 27,
        fat_g: 0.4,
        fiber_g: 3.1,
        sugar_g: 14,
        potassium_mg: 420,
        magnesium_mg: 32,
        vitamin_c_mg: 10,
        folate_ug: 24,
        water_ml: 90,
      },
      foodGroups: { ...emptyFoodGroupServes(), fruit: 0.8 },
    },
    {
      name: 'Skim milk',
      brand: null,
      basis: 'per_100g',
      servingGrams: null,
      servingLabel: null,
      nutrients: {
        ...emptyNutrientVector(),
        energy_kcal: 35,
        protein_g: 3.5,
        carbs_g: 5,
        fat_g: 0.1,
        sugar_g: 5,
        sodium_mg: 45,
        calcium_mg: 125,
        potassium_mg: 160,
        vitamin_b12_ug: 0.5,
        vitamin_d_ug: 1,
        water_ml: 91,
      },
      foodGroups: { ...emptyFoodGroupServes(), dairy_or_alt: 0.4 },
    },
  ],
}
